#Default Config by TristanCode
plugin:
  version: 1.1

stats:
  playercount: 0

motd:
  message: '&cHello, &chow are you?'
  
message:
  join: '&8[&2+&8]&7 %player% joined the game' 
  quit: '&8[&4-&8]&7 %player% left the game'
  welcome: '&eWelcome %player% to the server!'
