#Default config by tristanhonor
plugin:
  version: 1.5.1

stats:
  playercount: 0

motd:
  message: '&cHello, &cwelcome to the server'
  
message:
  join: '&8[&2+&8]&7 %player% joined the server'
  quit: '&8[&4-&8]&7 %player% left the server'
  welcome: '&eWelcome %player% to the server!'
